Homework-17
Otus-DevOps-2017-11/iPrior_microservices pull request #4
Opened 2018-03-09 18:38 UTC by iPrior

> Изменить docker-compose под кейс с множеством сетей, сетевых алиасов

Добавил две подсети. Настройки вынес в `.env` файл.

Наткнулся на "ошибку": 
в файле `./comment/Dockerfile` указано `ENV COMMENT_DATABASE_HOST comment_db` но "хоста" **comment_db** не существует - изменил на **post_db**

> Параметризуйте с помощью переменных окружений:
>
> • порт публикации сервиса ui
>
> • версии сервисов
>
> • возможно что-либо еще на ваше усмотрение
>

Помимо обозначенных в задании параметров, параметизировал подсети.

> Узнайте как образуется базовое имя проекта. Можно ли его задать? Если можно то как?

Имя контейнера можно задать параметром в `docker-compose.yml` - [container_name](https://docs.docker.com/compose/compose-file/#container_name)

2018-03-10 11:53 UTC, serjs commented on README.md
> +Наткнулся на "ошибку":
Посмотри на 15 слайд, мы там создаем net-alias для образов
`docker run -d --network=reddit --network-alias=post_db --network-
alias=comment_db mongo:latest`

Таким образом доступ есть по ним у сервисов. Чтобы это работало в compose, нужно добавить net-alias в него. В образах менять ничего не планируется.

2018-03-10 11:54 UTC, serjs requested changes
Привет!

Я отписал о изменениях связанных с Dockerfile. Больше замечаний нет

2018-03-10 11:56 UTC, iPrior commented on README.md
> +Наткнулся на "ошибку":
@serjs спасибо!
попробую разобраться

2018-03-15 08:02 UTC, serjs commented
Привет!

По этому заданию остались еще какие-то вопросы? Нужна ли помощь?

2018-03-15 08:27 UTC, iPrior commented
@serjs привет!
Спасибо, но я ещё даже не смотрел в сторону алиаса.
Я думаю если у меня возникнут вопросы, я в слак напишу.
Ещё раз спасибо!

2018-03-24 17:20 UTC, iPrior commented
@serjs вроде исправил: вернул ~в зад~ обратно `comment_db` , а в `docker-compose.yml` добавил алиас в `networks`

2018-03-29 07:45 UTC, serjs approved these changes

2018-03-29 07:46 UTC, serjs commented
Можно закрывать ПР 👍

2018-03-31 08:23 UTC, merged