Homework-21 [Monitoring 1]
Otus-DevOps-2017-11/iPrior_microservices pull request #7
Opened 2018-04-07 22:17 UTC by iPrior

Запустил инстанс с прометеем, разобрался с таргетами и экспортером.

[Ссылка на докер хаб](https://hub.docker.com/u/iprior/)

2018-04-10 15:07 UTC, Nklya requested changes
Подмерж мастер в эту ветку, убери из гитигнора `prometheus/` и закоммить собственно мониторинг.

2018-04-10 15:41 UTC, iPrior commented
@Nklya примержил мастер, поправил гитигнор, запушил мониторинг

2018-04-10 17:27 UTC, Nklya requested changes
Добрый вечер.

Иван, почти все выглядит ок.

Единственное, что у тебя в эту ветку попал хороший кусок следующего ДЗ.
Его нужно вычистить. Подробности ниже.

2018-04-10 17:27 UTC, Nklya commented on monitoring/prometheus/Dockerfile
> +ADD alerts.yml /etc/prometheus/
В первом ДЗ по мониторингу нет алертменеджера и алертов

2018-04-10 17:27 UTC, Nklya commented on monitoring/prometheus/alerts.yml
> +groups:
В первом ДЗ по мониторингу нет алертменеджера и алертов

2018-04-10 17:27 UTC, Nklya commented on monitoring/prometheus/prometheus.yml
> +rule_files:
В первом ДЗ по мониторингу нет алертменеджера и алертов

2018-04-10 17:27 UTC, Nklya commented on monitoring/prometheus/prometheus.yml
> +  - job_name: 'cadvisor'
И cadvisor с post тоже нет

2018-04-10 17:52 UTC, iPrior commented
ох.. мой косяк... `git add --all`
попробую отревертить

2018-04-13 17:15 UTC, iPrior commented
@Nklya вроде почистил

2018-04-13 17:18 UTC, Nklya approved these changes
Да, сейчас все ок 👍 

Этот PR нельзя пока мержить, пока 20 не смержится.
Но 23 ДЗ можешь сделать PR.

2018-04-13 17:20 UTC, iPrior commented
@Nklya спасибо!
Сейчас мастер волью в `montoring-2` и сделаю PR

2018-04-21 18:25 UTC, merged